### ISSUE TITLE
论文都发表了，写在论文里，github仓库为空

### ISSUE THREAD

**Issue by victorjiax** [mtbench101/mt-bench-101#2]
能不能有相关的中文多轮评测数据，中文太少了

**Comment by sefira** [comment]
Thank you all for your interest in MT-Bench-101! We are currently organizing the code and data. In the meantime, you can contact xingyuanbu@gmail.com to obtain the beta version, which can be run on an [OpenCompass](https://github.com/open-compass/opencompass)-based code branch. Thank you!
