### ISSUE TITLE
Call for code and data!

### ISSUE THREAD

**Issue by zemerov** [mtbench101/mt-bench-101#3]
The LLM community would higly appreciate if you release the code and data for the mt-bench-101. To the best of my knowledge it is the most comprehensive multi-turn doalogue. So I would like to run several extra models except the ones which were mentioned in the paper.

**Comment by sefira** [comment]
Thank you all for your interest in MT-Bench-101! We are currently organizing the code and data. In the meantime, you can contact xingyuanbu@gmail.com to obtain the beta version, which can be run on an [OpenCompass](https://github.com/open-compass/opencompass)-based code branch. Thank you!
